export interface BookingType {
    id: string,
    status: "PENDING" | "CONFIRMED" | "CANCELLED" | "COMPLETED",
    productId: string,
    productTitle: string,
    productAddress: {
        street: string,
        number: string,
        neighborhood: string,
        city: string,
        state: string,
    },
    productType: "SPACE" | "EQUIPMENT" | "SERVICE",
    spaceProduct?: {
        capacity: number,
        area: number,
    },
    equipmentProduct?: {
        brand: string,
        model: string,
        specifications: string,
        stock: number,
    },
    serviceProduct?: {
        durationMinutes: number,
        requirements: string,
    },
    productCategory: string,
    productImage: string[],
    institution: {
        email: string,
        phone: string,
    },
    productDiscount: number,
    client: {
        name: string,
        email: string,
        phone: string,
    },
    reservations: {
        date: string,
        hours: string[],
    }[],
    activityTitle: string,
    activityDescription: string,
    chargingType: "POR_HORA" | "POR_DIA" | null,
    totalAmount: number,
    finalAmount: number,
    paymentDate: Date | string,
}